# Generated by Django 4.0.6 on 2022-08-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='levels',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'UNDERGRADUATE'), ('Postgraduate', 'POSTGRADUATE'), ('Phd', 'PhD'), ('Others', 'OTHERS')], max_length=200, null=True, verbose_name='Levels'),
        ),
    ]
