# Generated by Django 4.0 on 2022-02-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='app',
            name='application_fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.CharField(max_length=512),
        ),
    ]
