# Generated by Django 4.0.7 on 2022-08-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, choices=[('Computer Science', 'COMPUTER SCIENCE'), ('STEM', 'STEM'), ('All', 'ALL'), ('Commerce', 'COMMERCE'), ('Science', 'SCIENCE'), ('Engineering', 'ENGINEERING'), ('Arts', 'ARTS'), ('MBA in HR', 'MBA IN HR'), ('MBA in Finance', 'MBA IN FINANCE'), ('Biology', 'BIOLOGY'), ('Law', 'LAW'), ('Medicine', 'MEDICINE'), ('Others', 'OTHERS')], max_length=4098, null=True, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, choices=[('BA', 'BA'), ('BSc', 'BSc'), ('BCom', 'BCom'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('MSc', 'MSc'), ('MCom', 'MCom'), ('MCA', 'MCA'), ('MPhil', 'MPhil'), ('PhD', 'PhD'), ('BTech', 'BTECH'), ('Others', 'Others')], max_length=4098, null=True, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.CharField(blank=True, choices=[('Singing', 'SINGING'), ('Dancing', 'DANCING'), ('Reading', 'READING'), ('Writing', 'WRITING'), ('Cooking', 'COOKING'), ('Sports', 'SPORTS'), ('Coding', 'CODING'), ('Robotics', 'ROBOTICS'), ('Android Development', 'ANDROID DEVELOPMENT'), ('Others', 'OTHERS')], max_length=4098, null=True, verbose_name='Skill'),
        ),
    ]
