# Generated by Django 4.0 on 2022-02-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_app_amount_alter_app_application_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='link',
            field=models.CharField(default=404, max_length=128),
            preserve_default=False,
        ),
    ]
