# Generated by Django 4.0.6 on 2022-08-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_app_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='applicationfees',
            field=models.CharField(max_length=4098, verbose_name='Application Fees'),
        ),
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.CharField(blank=True, choices=[('National', 'NATIONAL'), ('International', 'INTERNATIONAL')], max_length=4098, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='app',
            name='deadline',
            field=models.CharField(max_length=4098),
        ),
        migrations.AlterField(
            model_name='app',
            name='eligibilitycriteria',
            field=models.CharField(help_text='Enter Eligibility Criteria', max_length=4098, verbose_name='Eligibility Criteria'),
        ),
        migrations.AlterField(
            model_name='app',
            name='exam',
            field=models.CharField(help_text='Enter if any exam is required', max_length=4098),
        ),
        migrations.AlterField(
            model_name='app',
            name='levels',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'UNDERGRADUATE'), ('Postgraduate', 'POSTGRADUATE'), ('Phd', 'PhD'), ('Others', 'OTHERS')], max_length=4098, null=True, verbose_name='Levels'),
        ),
        migrations.AlterField(
            model_name='app',
            name='link',
            field=models.CharField(help_text='Enter 404 if not available', max_length=4098),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(help_text='Enter Name of Scholarship', max_length=4098),
        ),
        migrations.AlterField(
            model_name='app',
            name='providedby',
            field=models.CharField(help_text='Enter name of sponsor or organization', max_length=4098, verbose_name='Provided By'),
        ),
        migrations.AlterField(
            model_name='app',
            name='scholarshipamount',
            field=models.CharField(max_length=4098, verbose_name='Scholarship Amount'),
        ),
    ]
