# Generated by Django 4.0 on 2022-03-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_app_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='link',
            field=models.URLField(max_length=128),
        ),
    ]
